import Head from "next/head";
import {
  RiDownloadFill,
  RiNotification4Fill,
  RiShoppingCart2Fill,
} from "react-icons/ri";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Bar } from "react-chartjs-2";
import { faker } from "@faker-js/faker";
import { onAuthStateChanged } from "@/utils/auth";
import { useState, useEffect } from "react";
import { db } from "@/utils/firebaseService";
import { collection, getDoc, doc } from "firebase/firestore";
import { logout } from "../utils/auth.js";
import { useRouter } from "next/router";

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip
  // Legend
);

const options = {
  plugins: {
    title: {
      display: true,
      text: "Monthly Expenses",
    },
  },
  responsive: true,
  scales: {
    x: {
      stacked: true,
    },
    y: {
      stacked: true,
    },
  },
};

const labels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"];

const data = {
  labels,
  datasets: [
    {
      label: "Dataset 1",
      data: labels.map(() => faker.datatype.number({ min: 0, max: 100 })),
      backgroundColor: "rgb(255, 99, 132)",
    },
    {
      label: "Dataset 2",
      data: labels.map(() => faker.datatype.number({ min: 0, max: 100 })),
      backgroundColor: "rgb(75, 192, 192)",
    },
    {
      label: "Dataset 3",
      data: labels.map(() => faker.datatype.number({ min: 0, max: 100 })),
      backgroundColor: "rgb(53, 162, 235)",
    },
  ],
};

export default function Home() {
  const [user, setUser] = useState(null);
  const Router = useRouter();
  // onAuthStateChanged(async (user) => {
  //   if (user) {
  //     const docSnap = await getDoc(doc(db, "users", user.uid));
  //     setUser(docSnap.data());
  //     console.log(docSnap.data());
  //   } else {
  //     Router.push("/login");
  //   }
  // });
  // useEffect(() => {
  //   onAuthStateChanged(async (user) => {
  //     const docSnap = await getDoc(doc(db, "users", user.uid));
  //     setUser(docSnap.data());
  //   });
  //   if (!user) Router.push("/login");
  // }, []);
  useEffect(() => {
    const unlisten = onAuthStateChanged(async (authUser) => {
      if (authUser) {
        const docSnap = await getDoc(doc(db, "users", authUser.uid));
        setUser(docSnap.data());
      } else {
        Router.push("/login");
      }
    });
  },[Router]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="w-full flex flex-col gap-10">
        <div className="inline-flex space-x-20 items-center justify-between w-full">
          <div className="flex space-x-2.5 items-center justify-start">
            {user && (
              <img
                onClick={logout}
                className="w-12 h-12 border rounded-full"
                src="https://cdn.discordapp.com/avatars/720862118244515860/15460e9328036466028b68522ee422ab.png?size=1024"
              />
            )}
            <div className="inline-flex flex-col items-start justify-start">
              <p className="text-xs font-medium tracking-wide leading-tight text-gray-400">
                Welcome back
              </p>
              <p className="text-lg font-semibold tracking-wide leading-relaxed text-gray-800">
                {user && user.name}
              </p>
            </div>
          </div>
          <div className="relative">
            <RiNotification4Fill size={24} />
          </div>
        </div>
        <div className="inline-flex space-x-4 items-start justify-between w-full">
          <div className="inline-flex flex-col space-y-2 items-start justify-start w-40 h-full p-4 bg-white border rounded-2xl border-gray-200">
            <div className="flex w-12 h-12 items-center justify-center flex-1  p-3 bg-gray-200 rounded-xl">
              <RiDownloadFill color="green" size={24} />
            </div>
            <p className="text-base font-semibold tracking-wide leading-normal text-gray-800">
              ₹{user && user.income}
            </p>
            <p className="text-sm font-medium tracking-wide leading-snug text-gray-400">
              Income
            </p>
          </div>
          <div className="inline-flex flex-col space-y-2 items-start justify-start w-40 p-4 bg-white border rounded-2xl border-gray-200">
            <div className="flex w-12 h-12 items-center justify-center flex-1 p-3 bg-gray-200 rounded-xl">
              <RiDownloadFill color="red" size={24} className="rotate-180" />
            </div>
            <p className="text-base font-semibold tracking-wide leading-normal text-gray-800">
              ₹4,764.35
            </p>
            <p className="text-sm font-medium tracking-wide leading-snug text-gray-400">
              Expense
            </p>
          </div>
        </div>
        <div className="inline-flex flex-col space-y-2.5 items-start justify-start w-full">
          <p className="text-base font-semibold tracking-wide leading-normal text-gray-800">
            Most spent on
          </p>
          <div className="inline-flex space-x-32 items-center justify-between w-full">
            <div className="flex space-x-3 items-center justify-start">
              <div className="flex w-12 h-12 items-center justify-center flex-1 p-3 bg-gray-200 rounded-xl">
                <RiShoppingCart2Fill color="red" size={24} />
              </div>
              <div className="inline-flex flex-col space-y-0.5 items-start justify-start">
                <p className="text-sm font-semibold tracking-wide leading-snug text-gray-800">
                  Shopping
                </p>
                <p className="text-xs font-medium tracking-wide leading-tight text-gray-400">
                  Clothes, Gadgets etc
                </p>
              </div>
            </div>
            <p className="text-base font-semibold tracking-wide leading-normal text-gray-800">
              ₹433,00
            </p>
          </div>
          <hr className="w-full h-0.5 border-gray-100 pb-4" />
          <div className="border-gray-200 p-4 border rounded-2xl ">
            <Bar options={options} data={data} />
          </div>
        </div>
        <div className="inline-flex flex-col space-y-2.5 items-start justify-start w-full">
          <p className="text-base font-semibold tracking-wide leading-normal text-gray-800">
            Quote of the day
          </p>
          <div className="inline-flex items-center justify-center w-full ">
            <p className="text-sm font-medium tracking-wide leading-snug text-center text-gray-800">
              “Zindagi mea sabko Paisa kamana hea padta”
              <br />- Bhavin
            </p>
          </div>
          <div className="w-80 h-0.5 border-gray-100" />
        </div>
      </section>
    </>
  );
}
